export GOPATH=$HOME/go
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:/usr/local/bin:/usr/local/sbin:$HOME/bin:$HOME/.local/bin:${GOPATH//://bin:}/bin:$PATH"
export REUSE_DOCKER=1
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
export PATH="/opt/homebrew/bin:$PATH"
